name: Vercel Cron Job

on:
  schedule:
    - cron: "*/1 * * * *"  # Runs every minute
  workflow_dispatch:  # Allows manual triggering

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Call Vercel API
        run: curl -X GET https://new-corn.vercel.app/add
